//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioCoches.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conductor
    {
        public Conductor()
        {
            this.Licencias = new HashSet<Licencias>();
        }
    
        public int idConductor { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public Nullable<int> idVehiculo { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
        public virtual ICollection<Licencias> Licencias { get; set; }
    }
}
